import { Pipe, PipeTransform } from '@angular/core';
import { ROLES } from '@pang/const';

@Pipe({
  name: 'countryFlag',
})
export class CountryFlagPipe implements PipeTransform {
  transform(countryISO: string): string {
    const code = countryISO;
    switch (code) {
      case 'AF':
        return '🇦🇫';
      case 'AX':
        return '🇦🇽';
      case 'AL':
        return '🇦🇱';
      case 'DZ':
        return '🇩🇿';
      case 'AS':
        return '🇼🇸';
      case 'AD':
        return '🇦🇩';
      case 'AI':
        return '🇦🇴';
      case 'AQ':
        return '🇦🇶';
      case 'AG':
        return '🇦🇬';
      case 'AR':
        return '🇦🇷';
      case 'AM':
        return '🇦🇲';
      case 'AW':
        return '🇦🇼';
      case 'AU':
        return '🇦🇺';
      case 'AT':
        return '🇦🇹';
      case 'AZ':
        return '🇦🇿';
      case 'BS':
        return '🇧🇸';
      case 'BH':
        return '🇧🇭';
      case 'BD':
        return '🇧🇩';
      case 'BB':
        return '🇧🇧';
      case 'BY':
        return '🇧🇾';
      case 'BE':
        return '🇧🇪';
      case 'BZ':
        return '🇧🇿';
      case 'BJ':
        return '🇧🇯';
      case 'BM':
        return '🇧🇲';
      case 'BT':
        return '🇧🇹';
      case 'BO':
        return '🇧🇴';
      case 'BA':
        return '🇧🇦';
      case 'BV':
        return '🇧🇻';
      case 'BR':
        return '🇧🇷';
      case 'IO':
        return '🇮🇴';
      case 'BN':
        return '🇧🇳';
      case 'BG':
        return '🇧🇬';
      case 'BF':
        return '🇧🇫';
      case 'BI':
        return '🇧🇮';
      case 'KH':
        return '🇰🇭';
      case 'CM':
        return '🇨🇲';
      case 'CA':
        return '🇨🇦';
      case 'CV':
        return '🇨🇻';
      case 'KY':
        return '🇰🇾';
      case 'CF':
        return '🇨🇫';
      case 'TD':
        return '🇹🇩';
      case 'CL':
        return '🇨🇱';
      case 'CN':
        return '🇨🇳';
      case 'CX':
        return '🇨🇽';
      case 'CC':
        return '🇨🇨';
      case 'CO':
        return '🇨🇴';
      case 'KM':
        return '🇰🇲';
      case 'CG':
        return '🇨🇬';
      case 'CD':
        return '🇨🇩';
      case 'CK':
        return '🇨🇰';
      case 'CR':
        return '🇨🇷';
      case 'CI':
        return '🇨🇮';
      case 'HR':
        return '🇭🇷';
      case 'CU':
        return '🇨🇺';
      case 'CY':
        return '🇨🇾';
      case 'CZ':
        return '🇨🇿';
      case 'DK':
        return '🇩🇰';
      case 'DJ':
        return '🇩🇯';
      case 'DM':
        return '🇩🇲';
      case 'DO':
        return '🇩🇴';
      case 'EC':
        return '🇪🇨';
      case 'EG':
        return '🇪🇬';
      case 'SV':
        return '🇸🇻';
      case 'GQ':
        return '🇬🇶';
      case 'ER':
        return '🇪🇷';
      case 'EE':
        return '🇪🇪';
      case 'ET':
        return '🇪🇹';
      case 'FK':
        return '🇫🇰';
      case 'FO':
        return '🇫🇴';
      case 'FJ':
        return '🇫🇯';
      case 'FI':
        return '🇫🇮';
      case 'FR':
        return '🇫🇷';
      case 'GF':
        return '🇬🇫';
      case 'PF':
        return '🇵🇫';
      case 'TF':
        return '🇹🇫';
      case 'GA':
        return '🇬🇦';
      case 'GM':
        return '🇬🇲';
      case 'GE':
        return '🇬🇪';
      case 'DE':
        return '🇩🇪';
      case 'GH':
        return '🇬🇭';
      case 'GI':
        return '🇬🇮';
      case 'GR':
        return '🇬🇷';
      case 'GL':
        return '🇬🇱';
      case 'GD':
        return '🇬🇩';
      case 'GP':
        return '🇬🇵';
      case 'GU':
        return '🇬🇺';
      case 'GT':
        return '🇬🇹';
      case 'GG':
        return '🇬🇬';
      case 'GN':
        return '🇬🇳';
      case 'GW':
        return '🇬🇼';
      case 'GY':
        return '🇬🇾';
      case 'HT':
        return '🇭🇹';
      case 'HM':
        return '🇭🇲';
      case 'VA':
        return '🇻🇦';
      case 'HN':
        return '🇭🇳';
      case 'HK':
        return '🇭🇰';
      case 'HU':
        return '🇭🇺';
      case 'IS':
        return '🇮🇸';
      case 'IN':
        return '🇮🇳';
      case 'ID':
        return '🇮🇩';
      case 'IR':
        return '🇮🇷';
      case 'IQ':
        return '🇮🇶';
      case 'IE':
        return '🇮🇪';
      case 'IM':
        return '🇮🇲';
      case 'IL':
        return '🇮🇱';
      case 'IT':
        return '🇮🇹';
      case 'JM':
        return '🇯🇲';
      case 'JP':
        return '🇯🇵';
      case 'JE':
        return '🇯🇪';
      case 'JO':
        return '🇯🇴';
      case 'KZ':
        return '🇰🇿';
      case 'KE':
        return '🇰🇪';
      case 'KI':
        return '🇰🇮';
      case 'KP':
        return '🇰🇵';
      case 'KR':
        return '🇰🇷';
      case 'KW':
        return '🇰🇼';
      case 'KG':
        return '🇰🇬';
      case 'LA':
        return '🇱🇦';
      case 'LV':
        return '🇱🇻';
      case 'LB':
        return '🇱🇧';
      case 'LS':
        return '🇱🇸';
      case 'LY':
        return '🇱🇾';
      case 'LI':
        return '🇱🇮';
      case 'LT':
        return '🇱🇹';
      case 'LU':
        return '🇱🇺';
      case 'MO':
        return '🇲🇴';
      case 'MK':
        return '🇲🇰';
      case 'MG':
        return '🇲🇬';
      case 'MW':
        return '🇲🇼';
      case 'MY':
        return '🇲🇾';
      case 'MV':
        return '🇲🇻';
      case 'ML':
        return '🇲🇱';
      case 'MT':
        return '🇲🇹';
      case 'MH':
        return '🇲🇭';
      case 'MQ':
        return '🇲🇶';
      case 'MR':
        return '🇲🇷';
      case 'MU':
        return '🇲🇺';
      case 'YT':
        return '🇾🇹';
      case 'MX':
        return '🇲🇽';
      case 'FM':
        return '🇫🇲';
      case 'MD':
        return '🇲🇩';
      case 'MC':
        return '🇲🇨';
      case 'MN':
        return '🇲🇳';
      case 'MS':
        return '🇲🇸';
      case 'MA':
        return '🇲🇦';
      case 'MZ':
        return '🇲🇿';
      case 'MM':
        return '🇲🇲';
      case 'NA':
        return '🇳🇦';
      case 'NR':
        return '🇳🇷';
      case 'NP':
        return '🇳🇵';
      case 'NL':
        return '🇳🇱';
      case 'AN':
        return '🇧🇶';
      case 'NC':
        return '🇳🇨';
      case 'NZ':
        return '🇳🇿';
      case 'NI':
        return '🇳🇮';
      case 'NE':
        return '🇳🇪';
      case 'NG':
        return '🇳🇬';
      case 'NU':
        return '🇳🇺';
      case 'NF':
        return '🇳🇫';
      case 'MP':
        return '🇲🇵';
      case 'NO':
        return '🇳🇴';
      case 'OM':
        return '🇴🇲';
      case 'PK':
        return '🇵🇰';
      case 'PW':
        return '🇵🇼';
      case 'PS':
        return '🇵🇸';
      case 'PA':
        return '🇵🇦';
      case 'PG':
        return '🇵🇬';
      case 'PY':
        return '🇵🇾';
      case 'PE':
        return '🇵🇪';
      case 'PH':
        return '🇵🇭';
      case 'PN':
        return '🇵🇳';
      case 'PL':
        return '🇵🇱';
      case 'PT':
        return '🇵🇹';
      case 'PR':
        return '🇵🇷';
      case 'QA':
        return '🇶🇦';
      case 'RE':
        return '🇷🇪';
      case 'RO':
        return '🇷🇴';
      case 'RU':
        return '🇷🇺';
      case 'RW':
        return '🇷🇼';
      case 'SH':
        return '🇸🇭';
      case 'KN':
        return '🇰🇳';
      case 'LC':
        return '🇱🇨';
      case 'PM':
        return '🇵🇲';
      case 'VC':
        return '🇻🇨';
      case 'WS':
        return '🇼🇸';
      case 'SM':
        return '🇸🇲';
      case 'ST':
        return '🇸🇹';
      case 'SA':
        return '🇸🇦';
      case 'SN':
        return '🇸🇳';
      case 'CS':
        return '🇷🇸';
      case 'SC':
        return '🇸🇨';
      case 'SL':
        return '🇸🇱';
      case 'SG':
        return '🇸🇬';
      case 'SK':
        return '🇸🇰';
      case 'SI':
        return '🇸🇮';
      case 'SB':
        return '🇸🇧';
      case 'SO':
        return '🇸🇴';
      case 'ZA':
        return '🇿🇦';
      case 'GS':
        return '🇬🇸';
      case 'ES':
        return '🇪🇸';
      case 'LK':
        return '🇱🇰';
      case 'SD':
        return '🇸🇩';
      case 'SR':
        return '🇸🇷';
      case 'SJ':
        return '🇸🇯';
      case 'SZ':
        return '🇸🇿';
      case 'SE':
        return '🇸🇪';
      case 'CH':
        return '🇨🇭';
      case 'SY':
        return '🇸🇾';
      case 'TW':
        return '🇹🇼';
      case 'TJ':
        return '🇹🇯';
      case 'TZ':
        return '🇹🇿';
      case 'TH':
        return '🇹🇭';
      case 'TL':
        return '🇹🇱';
      case 'TG':
        return '🇹🇬';
      case 'TK':
        return '🇹🇰';
      case 'TO':
        return '🇹🇴';
      case 'TT':
        return '🇹🇹';
      case 'TN':
        return '🇹🇳';
      case 'TR':
        return '🇹🇷';
      case 'TM':
        return '🇹🇲';
      case 'TC':
        return '🇹🇨';
      case 'TV':
        return '🇹🇻';
      case 'UG':
        return '🇺🇬';
      case 'UA':
        return '🇺🇦';
      case 'AE':
        return '🇦🇪';
      case 'GB':
        return '🇬🇧';
      case 'US':
        return '🇺🇸';
      case 'UM':
        return '🇺🇲';
      case 'UY':
        return '🇺🇾';
      case 'UZ':
        return '🇺🇿';
      case 'VU':
        return '🇻🇺';
      case 'VE':
        return '🇻🇪';
      case 'VN':
        return '🇻🇳';
      case 'VG':
        return '🇻🇬';
      case 'VI':
        return '🇻🇮';
      case 'WF':
        return '🇼🇫';
      case 'EH':
        return '🇪🇭';
      case 'YE':
        return '🇾🇪';
      case 'ZM':
        return '🇿🇲';
      case 'ZW':
        return '🇿🇼';
      default:
        return null;
    }
  }
}
